"""Initial migration after reset

Revision ID: 940702c82923
Revises: 
Create Date: 2026-04-15 09:01:36.283514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940702c82923'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('id_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fullname', sa.String(length=128), nullable=False),
    sa.Column('nip', sa.String(length=64), nullable=True),
    sa.Column('job_title', sa.String(length=128), nullable=True),
    sa.Column('qr_code', sa.String(length=128), nullable=False),
    sa.Column('id_card_image_path', sa.String(length=256), nullable=True),
    sa.Column('phash_value', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_table('logbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_card_id', sa.Integer(), nullable=True),
    sa.Column('petugas_id', sa.Integer(), nullable=True),
    sa.Column('scan_image_path', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_card_id'], ['id_cards.id'], ),
    sa.ForeignKeyConstraint(['petugas_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logbooks')
    op.drop_table('id_cards')
    op.drop_table('users')
    # ### end Alembic commands ###
